### ISSUE TITLE
Nadles horror!

### ISSUE THREAD

**Issue by fakuferrari** [YZYLAB/solana-trade-bot#1]
@YZYLAB  I'm going crazy with the nadles configuration........... :(

**Comment by YZYLAB** [comment]
There isn’t much or any configuration for that so not sure what you are
stuck on?

Op za 12 okt 2024 om 03:02 schreef fakuferrari ***@***.***>

**Comment by fakuferrari** [comment]
@YZYLAB Hello :D
Based on the robot's configuration, should the Nadles API be placed in the API Key section of Billing Token, or is there something else to do? I’ve never used Nadles before, and being an amateur at this, plus Spanish-speaking with little knowledge of English, I haven’t been able to set it up. How many Endpoints need to be configured?

Thank you, and sorry for bothering you!

**Comment by fakuferrari** [comment]
@YZYLAB hello :D
Based on the robot's configuration, should the Nadles API be placed in the API Key section of Billing Token, or is there something else to do? I’ve never used Nadles before, and being an amateur at this, plus Spanish-speaking with little knowledge of English, I haven’t been able to set it up. How many Endpoints need to be configured?

Thank you, and sorry for bothering you!

**Comment by YZYLAB** [comment]
You don't need to configure anything on nadles. I just pushed an update that uses the new data api. 
You just need to subscribe here https://www.solanatracker.io/data-api and enter your api key in the .env

**Comment by fakuferrari** [comment]
@YZYLAB 
Thank you!
Yesterday I followed those same steps, but they didn’t work for me. Having the billing token in the index section didn’t allow it to work.
Thank you so much for the help!
