### ISSUE TITLE
 node index.js 2024-10-27 02:03:19 info: Starting Trading Bot 2024-10-27 02:03:19 error: Error in bot execution

### ISSUE THREAD

**Issue by dedelonxe** [YZYLAB/solana-trade-bot#2]
node index.js
2024-10-27 02:03:19 info: Starting Trading Bot
2024-10-27 02:03:19 error: Error in bot execution

can i use 

RPC_URL="https://api.mainnet-beta.solana.com"
WS_URL="wss://api.mainnet-beta.solana.com"

**Comment by YZYLAB** [comment]
No, you can’t use solana’s public rpc.

Op zo 27 okt 2024 om 03:05 schreef dedelonxe ***@***.***>

**Comment by dedelonxe** [comment]
okay i need https://www.solanatracker.io/?

**Comment by YZYLAB** [comment]
You can get an RPC here: https://www.solanatracker.io/solana-rpc
